# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Portfolio
tagline:          'Portfolio - Henry Glick'
description:      'Henry Glick'
site_url:              https://github.com/hglick/hglick.github.io/   
# old URL: http://hyde.getpoole.com
baseurl:          /

author:
  name:           'H'

paginate:         5

# Custom vars
version:          2.1.0

