# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Portfolio
tagline:          'Portfolio - Henry Glick'
description:      'Henry Glick'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'H. Glick'

paginate:         5

# Custom vars
version:          2.1.0

